# Generated by Django 4.2.4 on 2023-08-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='com_profile',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='req',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
